package cat.descobreix.sacs

import androidx.compose.ui.graphics.Color
import cat.descobreix.R

// Generat per disseny/sacs/gen-recursos.py a partir de la configuració del joc i dels dissenys: no l'editis a mà.

/** El nom de cada cosa de la col·lecció (strings.xml). */
internal val NOMS_OBJECTES: Map<String, Int> = mapOf(
    "emoji:anims--bateria" to R.string.emoji_anims__bateria,
    "emoji:anims--bota" to R.string.emoji_anims__bota,
    "emoji:anims--castell" to R.string.emoji_anims__castell,
    "emoji:anims--cim" to R.string.emoji_anims__cim,
    "emoji:anims--fanal" to R.string.emoji_anims__fanal,
    "emoji:anims--foc" to R.string.emoji_anims__foc,
    "emoji:anims--gairebe" to R.string.emoji_anims__gairebe,
    "emoji:cares--aimare" to R.string.emoji_cares__aimare,
    "emoji:cares--alucino" to R.string.emoji_cares__alucino,
    "emoji:cares--atope" to R.string.emoji_cares__atope,
    "emoji:cares--atxim" to R.string.emoji_cares__atxim,
    "emoji:cares--balla" to R.string.emoji_cares__balla,
    "emoji:cares--bravo" to R.string.emoji_cares__bravo,
    "emoji:cares--bull" to R.string.emoji_cares__bull,
    "emoji:cares--content" to R.string.emoji_cares__content,
    "emoji:cares--dormint" to R.string.emoji_cares__dormint,
    "emoji:cares--ei" to R.string.emoji_cares__ei,
    "emoji:cares--enamorat" to R.string.emoji_cares__enamorat,
    "emoji:cares--fastic" to R.string.emoji_cares__fastic,
    "emoji:cares--festa" to R.string.emoji_cares__festa,
    "emoji:cares--flipo" to R.string.emoji_cares__flipo,
    "emoji:cares--fred" to R.string.emoji_cares__fred,
    "emoji:cares--gana" to R.string.emoji_cares__gana,
    "emoji:cares--llengua" to R.string.emoji_cares__llengua,
    "emoji:cares--malalt" to R.string.emoji_cares__malalt,
    "emoji:cares--mareig" to R.string.emoji_cares__mareig,
    "emoji:cares--mars" to R.string.emoji_cares__mars,
    "emoji:cares--mentida" to R.string.emoji_cares__mentida,
    "emoji:cares--musica" to R.string.emoji_cares__musica,
    "emoji:cares--mut" to R.string.emoji_cares__mut,
    "emoji:cares--niidea" to R.string.emoji_cares__niidea,
    "emoji:cares--no" to R.string.emoji_cares__no,
    "emoji:cares--pensant" to R.string.emoji_cares__pensant,
    "emoji:cares--peta" to R.string.emoji_cares__peta,
    "emoji:cares--peto" to R.string.emoji_cares__peto,
    "emoji:cares--por" to R.string.emoji_cares__por,
    "emoji:cares--riure" to R.string.emoji_cares__riure,
    "emoji:cares--rofl" to R.string.emoji_cares__rofl,
    "emoji:cares--salut" to R.string.emoji_cares__salut,
    "emoji:cares--sant" to R.string.emoji_cares__sant,
    "emoji:cares--selfie" to R.string.emoji_cares__selfie,
    "emoji:cares--senyor" to R.string.emoji_cares__senyor,
    "emoji:cares--si" to R.string.emoji_cares__si,
    "emoji:cares--son" to R.string.emoji_cares__son,
    "emoji:cares--sorpres" to R.string.emoji_cares__sorpres,
    "emoji:cares--trapella" to R.string.emoji_cares__trapella,
    "emoji:cares--trist" to R.string.emoji_cares__trist,
    "emoji:cares--ulleres" to R.string.emoji_cares__ulleres,
    "emoji:cares--ullsalcel" to R.string.emoji_cares__ullsalcel,
    "emoji:cares--xalant" to R.string.emoji_cares__xalant,
    "emoji:celebrar--brindis" to R.string.emoji_celebrar__brindis,
    "emoji:celebrar--cor" to R.string.emoji_celebrar__cor,
    "emoji:celebrar--globus" to R.string.emoji_celebrar__globus,
    "emoji:celebrar--medalla" to R.string.emoji_celebrar__medalla,
    "emoji:celebrar--pastis" to R.string.emoji_celebrar__pastis,
    "emoji:celebrar--petard" to R.string.emoji_celebrar__petard,
    "emoji:celebrar--sardana" to R.string.emoji_celebrar__sardana,
    "emoji:celebrar--traca" to R.string.emoji_celebrar__traca,
    "emoji:celebrar--trofeu" to R.string.emoji_celebrar__trofeu,
    "emoji:comentar--alerta" to R.string.emoji_comentar__alerta,
    "emoji:comentar--bolet" to R.string.emoji_comentar__bolet,
    "emoji:comentar--caganer" to R.string.emoji_comentar__caganer,
    "emoji:comentar--cobertura" to R.string.emoji_comentar__cobertura,
    "emoji:comentar--llibreta" to R.string.emoji_comentar__llibreta,
    "emoji:comentar--lloc" to R.string.emoji_comentar__lloc,
    "emoji:comentar--onets" to R.string.emoji_comentar__onets,
    "emoji:del-dia--barretina" to R.string.emoji_del_dia__barretina,
    "emoji:del-dia--calcot" to R.string.emoji_del_dia__calcot,
    "emoji:del-dia--calor" to R.string.emoji_del_dia__calor,
    "emoji:del-dia--lluna" to R.string.emoji_del_dia__lluna,
    "emoji:del-dia--ninot" to R.string.emoji_del_dia__ninot,
    "emoji:del-dia--pa" to R.string.emoji_del_dia__pa,
    "emoji:del-dia--pluja" to R.string.emoji_del_dia__pluja,
    "emoji:del-dia--sol" to R.string.emoji_del_dia__sol,
    "emoji:festes--bastons" to R.string.emoji_festes__bastons,
    "emoji:festes--capgros" to R.string.emoji_festes__capgros,
    "emoji:festes--cava" to R.string.emoji_festes__cava,
    "emoji:festes--correfoc" to R.string.emoji_festes__correfoc,
    "emoji:festes--drac" to R.string.emoji_festes__drac,
    "emoji:festes--estel" to R.string.emoji_festes__estel,
    "emoji:festes--fira" to R.string.emoji_festes__fira,
    "emoji:festes--revetlla" to R.string.emoji_festes__revetlla,
    "emoji:festes--santjordi" to R.string.emoji_festes__santjordi,
    "emoji:festes--tio" to R.string.emoji_festes__tio,
    "emoji:ruta--bici" to R.string.emoji_ruta__bici,
    "emoji:ruta--bruixola" to R.string.emoji_ruta__bruixola,
    "emoji:ruta--camera" to R.string.emoji_ruta__camera,
    "emoji:ruta--cartell" to R.string.emoji_ruta__cartell,
    "emoji:ruta--cotxe" to R.string.emoji_ruta__cotxe,
    "emoji:ruta--gr" to R.string.emoji_ruta__gr,
    "emoji:ruta--motxilla" to R.string.emoji_ruta__motxilla,
    "emoji:ruta--tenda" to R.string.emoji_ruta__tenda,
    "emoji:taula--caragol" to R.string.emoji_taula__caragol,
    "emoji:terra--bosc" to R.string.emoji_terra__bosc,
    "emoji:terra--campana" to R.string.emoji_terra__campana,
    "emoji:terra--cascada" to R.string.emoji_terra__cascada,
    "emoji:terra--espardenya" to R.string.emoji_terra__espardenya,
    "emoji:terra--ovella" to R.string.emoji_terra__ovella,
    "emoji:terra--ruc" to R.string.emoji_terra__ruc,
    "emoji:vehicles--bus" to R.string.emoji_vehicles__bus,
    "emoji:vehicles--camper" to R.string.emoji_vehicles__camper,
    "emoji:vehicles--globusaer" to R.string.emoji_vehicles__globusaer,
    "emoji:vehicles--moto" to R.string.emoji_vehicles__moto,
    "emoji:vehicles--teleferic" to R.string.emoji_vehicles__teleferic,
    "emoji:vehicles--tractor" to R.string.emoji_vehicles__tractor,
    "emoji:vehicles--veler" to R.string.emoji_vehicles__veler,
    "portada:cuir" to R.string.portada_cuir,
    "portada:mar" to R.string.portada_mar,
    "portada:negre-plata" to R.string.portada_negre_plata,
    "portada:nit" to R.string.portada_nit,
    "portada:pirineu" to R.string.portada_pirineu,
    "portada:senyera" to R.string.portada_senyera,
    "portada:verd-bosc" to R.string.portada_verd_bosc,
    "portada:castellers" to R.string.portada_castellers,
    "portada:costa-brava" to R.string.portada_costa_brava,
    "portada:crema" to R.string.portada_crema,
    "portada:pedra-seca" to R.string.portada_pedra_seca,
    "portada:roses" to R.string.portada_roses,
    "portada:barretina" to R.string.portada_barretina,
    "portada:bolets" to R.string.portada_bolets,
    "portada:rajola" to R.string.portada_rajola,
    "portada:riu" to R.string.portada_riu,
    "portada:terrats" to R.string.portada_terrats,
    "animacio:bici" to R.string.animacio_bici,
    "animacio:bruixola" to R.string.animacio_bruixola,
    "animacio:gegants" to R.string.animacio_gegants,
    "animacio:ocell" to R.string.animacio_ocell,
    "animacio:onades" to R.string.animacio_onades,
    "animacio:punts" to R.string.animacio_punts,
    "animacio:bastons" to R.string.animacio_bastons,
    "animacio:globus" to R.string.animacio_globus,
    "animacio:segell" to R.string.animacio_segell,
    "animacio:campana" to R.string.animacio_campana,
    "animacio:caragol" to R.string.animacio_caragol,
    "animacio:castell" to R.string.animacio_castell,
    "animacio:rotllana" to R.string.animacio_rotllana,
    "animacio:sol-lluna" to R.string.animacio_sol_lluna,
    "animacio:cotxe" to R.string.animacio_cotxe,
    "animacio:espiga" to R.string.animacio_espiga,
    "color:blau-mar" to R.string.color_blau_mar,
    "color:llimona" to R.string.color_llimona,
    "color:rosa" to R.string.color_rosa,
    "color:verd-bosc" to R.string.color_verd_bosc,
    "color:vermell" to R.string.color_vermell,
    "color:aigua" to R.string.color_aigua,
    "color:cel" to R.string.color_cel,
    "color:lila" to R.string.color_lila,
    "color:turquesa" to R.string.color_turquesa,
    "color:cirera" to R.string.color_cirera,
    "color:lavanda" to R.string.color_lavanda,
    "color:pressec" to R.string.color_pressec,
    "color:salvia" to R.string.color_salvia,
    "color:plata" to R.string.color_plata,
)

/** La frase de cada emoji, la que es fa servir com a reacció. */
internal val FRASES_EMOJIS: Map<String, Int> = mapOf(
    "anims--bateria" to R.string.emoji_anims__bateria_frase,
    "anims--bota" to R.string.emoji_anims__bota_frase,
    "anims--castell" to R.string.emoji_anims__castell_frase,
    "anims--cim" to R.string.emoji_anims__cim_frase,
    "anims--fanal" to R.string.emoji_anims__fanal_frase,
    "anims--foc" to R.string.emoji_anims__foc_frase,
    "anims--gairebe" to R.string.emoji_anims__gairebe_frase,
    "cares--aimare" to R.string.emoji_cares__aimare_frase,
    "cares--alucino" to R.string.emoji_cares__alucino_frase,
    "cares--atope" to R.string.emoji_cares__atope_frase,
    "cares--atxim" to R.string.emoji_cares__atxim_frase,
    "cares--balla" to R.string.emoji_cares__balla_frase,
    "cares--bravo" to R.string.emoji_cares__bravo_frase,
    "cares--bull" to R.string.emoji_cares__bull_frase,
    "cares--content" to R.string.emoji_cares__content_frase,
    "cares--dormint" to R.string.emoji_cares__dormint_frase,
    "cares--ei" to R.string.emoji_cares__ei_frase,
    "cares--enamorat" to R.string.emoji_cares__enamorat_frase,
    "cares--fastic" to R.string.emoji_cares__fastic_frase,
    "cares--festa" to R.string.emoji_cares__festa_frase,
    "cares--flipo" to R.string.emoji_cares__flipo_frase,
    "cares--fred" to R.string.emoji_cares__fred_frase,
    "cares--gana" to R.string.emoji_cares__gana_frase,
    "cares--llengua" to R.string.emoji_cares__llengua_frase,
    "cares--malalt" to R.string.emoji_cares__malalt_frase,
    "cares--mareig" to R.string.emoji_cares__mareig_frase,
    "cares--mars" to R.string.emoji_cares__mars_frase,
    "cares--mentida" to R.string.emoji_cares__mentida_frase,
    "cares--musica" to R.string.emoji_cares__musica_frase,
    "cares--mut" to R.string.emoji_cares__mut_frase,
    "cares--niidea" to R.string.emoji_cares__niidea_frase,
    "cares--no" to R.string.emoji_cares__no_frase,
    "cares--pensant" to R.string.emoji_cares__pensant_frase,
    "cares--peta" to R.string.emoji_cares__peta_frase,
    "cares--peto" to R.string.emoji_cares__peto_frase,
    "cares--por" to R.string.emoji_cares__por_frase,
    "cares--riure" to R.string.emoji_cares__riure_frase,
    "cares--rofl" to R.string.emoji_cares__rofl_frase,
    "cares--salut" to R.string.emoji_cares__salut_frase,
    "cares--sant" to R.string.emoji_cares__sant_frase,
    "cares--selfie" to R.string.emoji_cares__selfie_frase,
    "cares--senyor" to R.string.emoji_cares__senyor_frase,
    "cares--si" to R.string.emoji_cares__si_frase,
    "cares--son" to R.string.emoji_cares__son_frase,
    "cares--sorpres" to R.string.emoji_cares__sorpres_frase,
    "cares--trapella" to R.string.emoji_cares__trapella_frase,
    "cares--trist" to R.string.emoji_cares__trist_frase,
    "cares--ulleres" to R.string.emoji_cares__ulleres_frase,
    "cares--ullsalcel" to R.string.emoji_cares__ullsalcel_frase,
    "cares--xalant" to R.string.emoji_cares__xalant_frase,
    "celebrar--brindis" to R.string.emoji_celebrar__brindis_frase,
    "celebrar--cor" to R.string.emoji_celebrar__cor_frase,
    "celebrar--globus" to R.string.emoji_celebrar__globus_frase,
    "celebrar--medalla" to R.string.emoji_celebrar__medalla_frase,
    "celebrar--pastis" to R.string.emoji_celebrar__pastis_frase,
    "celebrar--petard" to R.string.emoji_celebrar__petard_frase,
    "celebrar--sardana" to R.string.emoji_celebrar__sardana_frase,
    "celebrar--traca" to R.string.emoji_celebrar__traca_frase,
    "celebrar--trofeu" to R.string.emoji_celebrar__trofeu_frase,
    "comentar--alerta" to R.string.emoji_comentar__alerta_frase,
    "comentar--bolet" to R.string.emoji_comentar__bolet_frase,
    "comentar--caganer" to R.string.emoji_comentar__caganer_frase,
    "comentar--cobertura" to R.string.emoji_comentar__cobertura_frase,
    "comentar--llibreta" to R.string.emoji_comentar__llibreta_frase,
    "comentar--lloc" to R.string.emoji_comentar__lloc_frase,
    "comentar--onets" to R.string.emoji_comentar__onets_frase,
    "del-dia--barretina" to R.string.emoji_del_dia__barretina_frase,
    "del-dia--calcot" to R.string.emoji_del_dia__calcot_frase,
    "del-dia--calor" to R.string.emoji_del_dia__calor_frase,
    "del-dia--lluna" to R.string.emoji_del_dia__lluna_frase,
    "del-dia--ninot" to R.string.emoji_del_dia__ninot_frase,
    "del-dia--pa" to R.string.emoji_del_dia__pa_frase,
    "del-dia--pluja" to R.string.emoji_del_dia__pluja_frase,
    "del-dia--sol" to R.string.emoji_del_dia__sol_frase,
    "festes--bastons" to R.string.emoji_festes__bastons_frase,
    "festes--capgros" to R.string.emoji_festes__capgros_frase,
    "festes--cava" to R.string.emoji_festes__cava_frase,
    "festes--correfoc" to R.string.emoji_festes__correfoc_frase,
    "festes--drac" to R.string.emoji_festes__drac_frase,
    "festes--estel" to R.string.emoji_festes__estel_frase,
    "festes--fira" to R.string.emoji_festes__fira_frase,
    "festes--revetlla" to R.string.emoji_festes__revetlla_frase,
    "festes--santjordi" to R.string.emoji_festes__santjordi_frase,
    "festes--tio" to R.string.emoji_festes__tio_frase,
    "ruta--bici" to R.string.emoji_ruta__bici_frase,
    "ruta--bruixola" to R.string.emoji_ruta__bruixola_frase,
    "ruta--camera" to R.string.emoji_ruta__camera_frase,
    "ruta--cartell" to R.string.emoji_ruta__cartell_frase,
    "ruta--cotxe" to R.string.emoji_ruta__cotxe_frase,
    "ruta--gr" to R.string.emoji_ruta__gr_frase,
    "ruta--motxilla" to R.string.emoji_ruta__motxilla_frase,
    "ruta--tenda" to R.string.emoji_ruta__tenda_frase,
    "taula--caragol" to R.string.emoji_taula__caragol_frase,
    "terra--bosc" to R.string.emoji_terra__bosc_frase,
    "terra--campana" to R.string.emoji_terra__campana_frase,
    "terra--cascada" to R.string.emoji_terra__cascada_frase,
    "terra--espardenya" to R.string.emoji_terra__espardenya_frase,
    "terra--ovella" to R.string.emoji_terra__ovella_frase,
    "terra--ruc" to R.string.emoji_terra__ruc_frase,
    "vehicles--bus" to R.string.emoji_vehicles__bus_frase,
    "vehicles--camper" to R.string.emoji_vehicles__camper_frase,
    "vehicles--globusaer" to R.string.emoji_vehicles__globusaer_frase,
    "vehicles--moto" to R.string.emoji_vehicles__moto_frase,
    "vehicles--teleferic" to R.string.emoji_vehicles__teleferic_frase,
    "vehicles--tractor" to R.string.emoji_vehicles__tractor_frase,
    "vehicles--veler" to R.string.emoji_vehicles__veler_frase,
)

/** El dibuix de cada emoji. */
internal val DIBUIXOS_EMOJIS: Map<String, Int> = mapOf(
    "anims--bateria" to R.drawable.emoji_anims__bateria,
    "anims--bota" to R.drawable.emoji_anims__bota,
    "anims--castell" to R.drawable.emoji_anims__castell,
    "anims--cim" to R.drawable.emoji_anims__cim,
    "anims--fanal" to R.drawable.emoji_anims__fanal,
    "anims--foc" to R.drawable.emoji_anims__foc,
    "anims--gairebe" to R.drawable.emoji_anims__gairebe,
    "cares--aimare" to R.drawable.emoji_cares__aimare,
    "cares--alucino" to R.drawable.emoji_cares__alucino,
    "cares--atope" to R.drawable.emoji_cares__atope,
    "cares--atxim" to R.drawable.emoji_cares__atxim,
    "cares--balla" to R.drawable.emoji_cares__balla,
    "cares--bravo" to R.drawable.emoji_cares__bravo,
    "cares--bull" to R.drawable.emoji_cares__bull,
    "cares--content" to R.drawable.emoji_cares__content,
    "cares--dormint" to R.drawable.emoji_cares__dormint,
    "cares--ei" to R.drawable.emoji_cares__ei,
    "cares--enamorat" to R.drawable.emoji_cares__enamorat,
    "cares--fastic" to R.drawable.emoji_cares__fastic,
    "cares--festa" to R.drawable.emoji_cares__festa,
    "cares--flipo" to R.drawable.emoji_cares__flipo,
    "cares--fred" to R.drawable.emoji_cares__fred,
    "cares--gana" to R.drawable.emoji_cares__gana,
    "cares--llengua" to R.drawable.emoji_cares__llengua,
    "cares--malalt" to R.drawable.emoji_cares__malalt,
    "cares--mareig" to R.drawable.emoji_cares__mareig,
    "cares--mars" to R.drawable.emoji_cares__mars,
    "cares--mentida" to R.drawable.emoji_cares__mentida,
    "cares--musica" to R.drawable.emoji_cares__musica,
    "cares--mut" to R.drawable.emoji_cares__mut,
    "cares--niidea" to R.drawable.emoji_cares__niidea,
    "cares--no" to R.drawable.emoji_cares__no,
    "cares--pensant" to R.drawable.emoji_cares__pensant,
    "cares--peta" to R.drawable.emoji_cares__peta,
    "cares--peto" to R.drawable.emoji_cares__peto,
    "cares--por" to R.drawable.emoji_cares__por,
    "cares--riure" to R.drawable.emoji_cares__riure,
    "cares--rofl" to R.drawable.emoji_cares__rofl,
    "cares--salut" to R.drawable.emoji_cares__salut,
    "cares--sant" to R.drawable.emoji_cares__sant,
    "cares--selfie" to R.drawable.emoji_cares__selfie,
    "cares--senyor" to R.drawable.emoji_cares__senyor,
    "cares--si" to R.drawable.emoji_cares__si,
    "cares--son" to R.drawable.emoji_cares__son,
    "cares--sorpres" to R.drawable.emoji_cares__sorpres,
    "cares--trapella" to R.drawable.emoji_cares__trapella,
    "cares--trist" to R.drawable.emoji_cares__trist,
    "cares--ulleres" to R.drawable.emoji_cares__ulleres,
    "cares--ullsalcel" to R.drawable.emoji_cares__ullsalcel,
    "cares--xalant" to R.drawable.emoji_cares__xalant,
    "celebrar--brindis" to R.drawable.emoji_celebrar__brindis,
    "celebrar--cor" to R.drawable.emoji_celebrar__cor,
    "celebrar--globus" to R.drawable.emoji_celebrar__globus,
    "celebrar--medalla" to R.drawable.emoji_celebrar__medalla,
    "celebrar--pastis" to R.drawable.emoji_celebrar__pastis,
    "celebrar--petard" to R.drawable.emoji_celebrar__petard,
    "celebrar--sardana" to R.drawable.emoji_celebrar__sardana,
    "celebrar--traca" to R.drawable.emoji_celebrar__traca,
    "celebrar--trofeu" to R.drawable.emoji_celebrar__trofeu,
    "comentar--alerta" to R.drawable.emoji_comentar__alerta,
    "comentar--bolet" to R.drawable.emoji_comentar__bolet,
    "comentar--caganer" to R.drawable.emoji_comentar__caganer,
    "comentar--cobertura" to R.drawable.emoji_comentar__cobertura,
    "comentar--llibreta" to R.drawable.emoji_comentar__llibreta,
    "comentar--lloc" to R.drawable.emoji_comentar__lloc,
    "comentar--onets" to R.drawable.emoji_comentar__onets,
    "del-dia--barretina" to R.drawable.emoji_del_dia__barretina,
    "del-dia--calcot" to R.drawable.emoji_del_dia__calcot,
    "del-dia--calor" to R.drawable.emoji_del_dia__calor,
    "del-dia--lluna" to R.drawable.emoji_del_dia__lluna,
    "del-dia--ninot" to R.drawable.emoji_del_dia__ninot,
    "del-dia--pa" to R.drawable.emoji_del_dia__pa,
    "del-dia--pluja" to R.drawable.emoji_del_dia__pluja,
    "del-dia--sol" to R.drawable.emoji_del_dia__sol,
    "festes--bastons" to R.drawable.emoji_festes__bastons,
    "festes--capgros" to R.drawable.emoji_festes__capgros,
    "festes--cava" to R.drawable.emoji_festes__cava,
    "festes--correfoc" to R.drawable.emoji_festes__correfoc,
    "festes--drac" to R.drawable.emoji_festes__drac,
    "festes--estel" to R.drawable.emoji_festes__estel,
    "festes--fira" to R.drawable.emoji_festes__fira,
    "festes--revetlla" to R.drawable.emoji_festes__revetlla,
    "festes--santjordi" to R.drawable.emoji_festes__santjordi,
    "festes--tio" to R.drawable.emoji_festes__tio,
    "ruta--bici" to R.drawable.emoji_ruta__bici,
    "ruta--bruixola" to R.drawable.emoji_ruta__bruixola,
    "ruta--camera" to R.drawable.emoji_ruta__camera,
    "ruta--cartell" to R.drawable.emoji_ruta__cartell,
    "ruta--cotxe" to R.drawable.emoji_ruta__cotxe,
    "ruta--gr" to R.drawable.emoji_ruta__gr,
    "ruta--motxilla" to R.drawable.emoji_ruta__motxilla,
    "ruta--tenda" to R.drawable.emoji_ruta__tenda,
    "taula--caragol" to R.drawable.emoji_taula__caragol,
    "terra--bosc" to R.drawable.emoji_terra__bosc,
    "terra--campana" to R.drawable.emoji_terra__campana,
    "terra--cascada" to R.drawable.emoji_terra__cascada,
    "terra--espardenya" to R.drawable.emoji_terra__espardenya,
    "terra--ovella" to R.drawable.emoji_terra__ovella,
    "terra--ruc" to R.drawable.emoji_terra__ruc,
    "vehicles--bus" to R.drawable.emoji_vehicles__bus,
    "vehicles--camper" to R.drawable.emoji_vehicles__camper,
    "vehicles--globusaer" to R.drawable.emoji_vehicles__globusaer,
    "vehicles--moto" to R.drawable.emoji_vehicles__moto,
    "vehicles--teleferic" to R.drawable.emoji_vehicles__teleferic,
    "vehicles--tractor" to R.drawable.emoji_vehicles__tractor,
    "vehicles--veler" to R.drawable.emoji_vehicles__veler,
)

/** Les portades del passaport dels sacs: el fons (amb el dibuix), el daurat, el text i si porta la silueta de Catalunya. */
internal val PORTADES: Map<String, Portada> = mapOf(
    "cuir" to Portada(R.drawable.portada_cuir, Color(0xFF6B4224), Color(0xFFE9C9A0), Color(0xFFE9C9A0), true),
    "mar" to Portada(R.drawable.portada_mar, Color(0xFF11506E), Color(0xFFE8C36A), Color(0xFFE8C36A), true),
    "negre-plata" to Portada(R.drawable.portada_negre_plata, Color(0xFF121418), Color(0xFFC3CCD6), Color(0xFFC3CCD6), true),
    "nit" to Portada(R.drawable.portada_nit, Color(0xFF0E1430), Color(0xFFFFE3A3), Color(0xFFFFE3A3), true),
    "pirineu" to Portada(R.drawable.portada_pirineu, Color(0xFF2E4A6B), Color(0xFFF2F5F8), Color(0xFFF2F5F8), true),
    "senyera" to Portada(R.drawable.portada_senyera, Color(0xFFF2C230), Color(0xFF7A1418), Color(0xFF7A1418), false),
    "verd-bosc" to Portada(R.drawable.portada_verd_bosc, Color(0xFF1F4A33), Color(0xFFE8C36A), Color(0xFFE8C36A), true),
    "castellers" to Portada(R.drawable.portada_castellers, Color(0xFF5A1A20), Color(0xFFE8C36A), Color(0xFFE8C36A), true),
    "costa-brava" to Portada(R.drawable.portada_costa_brava, Color(0xFF1F7A8C), Color(0xFFF4EEDD), Color(0xFFF4EEDD), true),
    "crema" to Portada(R.drawable.portada_crema, Color(0xFFEFE6D2), Color(0xFFA87A2A), Color(0xFF7A5410), true),
    "pedra-seca" to Portada(R.drawable.portada_pedra_seca, Color(0xFF6E5E48), Color(0xFFF4EEDD), Color(0xFFF4EEDD), true),
    "roses" to Portada(R.drawable.portada_roses, Color(0xFFF3E6D6), Color(0xFF9E1C20), Color(0xFF9E1C20), true),
    "barretina" to Portada(R.drawable.portada_barretina, Color(0xFF1E1E22), Color(0xFFD7262B), Color(0xFFE8C36A), true),
    "bolets" to Portada(R.drawable.portada_bolets, Color(0xFF5A3A22), Color(0xFFF2C230), Color(0xFFF2C230), true),
    "rajola" to Portada(R.drawable.portada_rajola, Color(0xFF7A3324), Color(0xFFF4E4C8), Color(0xFFF4E4C8), true),
    "riu" to Portada(R.drawable.portada_riu, Color(0xFF2E4A3A), Color(0xFFE8C36A), Color(0xFFE8C36A), true),
    "terrats" to Portada(R.drawable.portada_terrats, Color(0xFF2A2F3A), Color(0xFFE8C36A), Color(0xFFE8C36A), true),
)

/** Els colors secundaris dels sacs. */
internal val COLORS: Map<String, Color> = mapOf(
    "blau-mar" to Color(0xFF4FA3E0),
    "llimona" to Color(0xFFE8D44D),
    "rosa" to Color(0xFFF07AAA),
    "verd-bosc" to Color(0xFF4CB782),
    "vermell" to Color(0xFFE5484D),
    "aigua" to Color(0xFF5ED6E0),
    "cel" to Color(0xFF8FD3F4),
    "lila" to Color(0xFFA27BEA),
    "turquesa" to Color(0xFF2EC4B6),
    "cirera" to Color(0xFFC2445A),
    "lavanda" to Color(0xFFB9A5E8),
    "pressec" to Color(0xFFFFB38A),
    "salvia" to Color(0xFF9CB89A),
    "plata" to Color(0xFFC3CCD6),
)
